### ISSUE TITLE
Can we do more lower-level stuffs?

### ISSUE THREAD

**Issue by siazeroli** [microsoft/NeuronBlocks#24]
After trying this project, I found that we may implement many upper-level tasks. However it is not easy for us to modify something lower-level such as word embedding. It would be helpful if it supports more lower-level stuffs on NLP. Thanks!

**Comment by ljshou** [comment]
Hi @siazeroli , thanks for your feedbacks. do you mean you want to train word embedding task? 
for this task, we will add it into our backlog and try to support in the near future. 

thanks,
Linjun
