### ISSUE TITLE
how to deal the large data when training model 

### ISSUE THREAD

**Issue by sano176** [microsoft/NeuronBlocks#53]
my compute have 70G memory, my training data  2G, the text classification of model_zoo  could not work.

**Comment by ljshou** [comment]
Hi @sano176  you are training on GPU right? Currently we are enabling laze load mode, which will solve your problem.

**Comment by sano176** [comment]
@ljshou  ok! Looking forward to updating

**Comment by chengfx** [comment]
Hi @sano176 . The lazy-load mechanism is being reviewed in this #50 . You can test this feature  using ***dev/fecheng*** branch in advance.

**Comment by sano176** [comment]
thank you very much, @chengfx ,  I will test it later and check if there are any problems.

**Comment by ljshou** [comment]
@sano176  have you got chance to take a try @chengfx's change?

**Comment by sano176** [comment]
It solved my problem， thank you very much!
