### ISSUE TITLE
no such file 'requirements.txt'

### ISSUE THREAD

**Issue by zyf3465** [microsoft/NeuronBlocks#54]
type “pip install -r requirements.txt“  and error  'no such file 'requirements.txt''

how to install ,thank u

**Comment by ljshou** [comment]
Hi @zyf3465  you need to go the root folder of NeuronBlocks. then run the above command.

**Comment by zyf3465** [comment]
thank u !!
------------------
-------------------------------------------------
祝工作愉快，事事顺心
 张翼飞
-------------------------------------------------

  


 




------------------ 原始邮件 ------------------
发件人: "L.J. SHOU"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 中午11:26
收件人: "microsoft/NeuronBlocks"<NeuronBlocks@noreply.github.com>;
抄送: "165381567"<165381567@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [microsoft/NeuronBlocks] no such file 'requirements.txt' (#54)




Hi @zyf3465  you need to go the root folder of NeuronBlocks. then run the above command.
