### ISSUE TITLE
Segmentation fault（error）

### ISSUE THREAD

**Issue by sano176** [microsoft/NeuronBlocks#56]
when i used the conf of text_classification  to fit data, i meet a segment default....
the max length  of my training data is 1500,  Is it caused by it?

**Comment by ljshou** [comment]
Hi @sano176  can you paste your error message? so we can take a look. Especially the place where the error was thrown?

**Comment by sano176** [comment]
there is no the stack information of exception and just a message "segmentation fault" ，i am not sure whether get more information about exception by "import traceback" 
i searched "torch segmentation fault" on google, someone suggested that decrease the number of batch.

**Comment by sano176** [comment]
@ljshou  there is no detail exception information on 
standard error output  and my error logging   ![image](https://user-images.githubusercontent.com/17269201/58449367-cb26ae80-80fa-11e9-921c-6da524ac0216.png)

**Comment by sano176** [comment]
it does't work while decreasing the number of batch .

**Comment by sano176** [comment]
it works well when i uninstall pytorch of version 0.4.1  and reinstall pytorch of version 1.0.1, thank you very much @ljshou . the  configuration of my computer is:
Linux version 3.10.0-327.28.3.el7.ttm.x86_64
gcc version 4.8.5
Red Hat 4.8.5-4
