### ISSUE TITLE
 Data skew problem

### ISSUE THREAD

**Issue by sano176** [microsoft/NeuronBlocks#63]
Does the configuartion of model_zoo  have an option to resolve the data skewing problem that 
a small number of categories be misclassified?

**Comment by adolphk-yk** [comment]
Hi sano, you can try setting weights for different classes in losses for data skewing problem.  We provided [example configuration file](https://github.com/microsoft/NeuronBlocks/blob/master/model_zoo/nlp_tasks/question_answer_matching/conf_question_answer_matching_bilstm.json)  for how to set weights in losses.

**Comment by ljshou** [comment]
losses": [
      {
        "type": "CrossEntropyLoss",
        "conf": {
          "weight": [0.1,0.9],
          "size_average": true
        },
        "inputs": ["output","label"]
